<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata about a feed, included in feed messages.
 *
 * Generated from protobuf message <code>FelixINX.TransitRealtime.FeedHeader</code>
 */
class FeedHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of the feed specification.
     * The current version is 1.0.
     * required string gtfs_realtime_version = 1;
     *
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     */
    private $gtfs_realtime_version = '';
    /**
     * optional Incrementality incrementality = 2 [default = FULL_DATASET];
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.FeedHeader.Incrementality incrementality = 2;</code>
     */
    private $incrementality = 0;
    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 3;
     *
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     */
    private $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gtfs_realtime_version
     *           Version of the feed specification.
     *           The current version is 1.0.
     *           required string gtfs_realtime_version = 1;
     *     @type int $incrementality
     *           optional Incrementality incrementality = 2 [default = FULL_DATASET];
     *     @type int|string $timestamp
     *           This timestamp identifies the moment when the content of this feed has been
     *           created (in server time). In POSIX time (i.e., number of seconds since
     *           January 1st 1970 00:00:00 UTC).
     *           optional uint64 timestamp = 3;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of the feed specification.
     * The current version is 1.0.
     * required string gtfs_realtime_version = 1;
     *
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     * @return string
     */
    public function getGtfsRealtimeVersion()
    {
        return $this->gtfs_realtime_version;
    }

    /**
     * Version of the feed specification.
     * The current version is 1.0.
     * required string gtfs_realtime_version = 1;
     *
     * Generated from protobuf field <code>string gtfs_realtime_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGtfsRealtimeVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->gtfs_realtime_version = $var;

        return $this;
    }

    /**
     * optional Incrementality incrementality = 2 [default = FULL_DATASET];
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @return int
     */
    public function getIncrementality()
    {
        return $this->incrementality;
    }

    /**
     * optional Incrementality incrementality = 2 [default = FULL_DATASET];
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.FeedHeader.Incrementality incrementality = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIncrementality($var)
    {
        GPBUtil::checkEnum($var, \FelixINX\TransitRealtime\FeedHeader_Incrementality::class);
        $this->incrementality = $var;

        return $this;
    }

    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 3;
     *
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * This timestamp identifies the moment when the content of this feed has been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 3;
     *
     * Generated from protobuf field <code>uint64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

