<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime\VehiclePosition;

/**
 * Congestion level that is affecting this vehicle.
 *
 * Protobuf type <code>FelixINX.TransitRealtime.VehiclePosition.CongestionLevel</code>
 */
class CongestionLevel
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_CONGESTION_LEVEL = 0;</code>
     */
    const UNKNOWN_CONGESTION_LEVEL = 0;
    /**
     * Generated from protobuf enum <code>RUNNING_SMOOTHLY = 1;</code>
     */
    const RUNNING_SMOOTHLY = 1;
    /**
     * Generated from protobuf enum <code>STOP_AND_GO = 2;</code>
     */
    const STOP_AND_GO = 2;
    /**
     * Generated from protobuf enum <code>CONGESTION = 3;</code>
     */
    const CONGESTION = 3;
    /**
     * People leaving their cars.
     *
     * Generated from protobuf enum <code>SEVERE_CONGESTION = 4;</code>
     */
    const SEVERE_CONGESTION = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CongestionLevel::class, \FelixINX\TransitRealtime\VehiclePosition_CongestionLevel::class);

