<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\Alert\Cause instead.
     * @deprecated
     */
    class Alert_Cause {}
}
class_exists(Alert\Cause::class);
@trigger_error('FelixINX\TransitRealtime\Alert_Cause is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\Alert\Cause instead', E_USER_DEPRECATED);

