<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\Alert\Effect instead.
     * @deprecated
     */
    class Alert_Effect {}
}
class_exists(Alert\Effect::class);
@trigger_error('FelixINX\TransitRealtime\Alert_Effect is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\Alert\Effect instead', E_USER_DEPRECATED);

