<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A selector for an entity in a GTFS feed.
 *
 * Generated from protobuf message <code>FelixINX.TransitRealtime.EntitySelector</code>
 */
class EntitySelector extends \Google\Protobuf\Internal\Message
{
    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * optional string agency_id = 1;
     *
     * Generated from protobuf field <code>string agency_id = 1;</code>
     */
    private $agency_id = '';
    /**
     * optional string route_id = 2;
     *
     * Generated from protobuf field <code>string route_id = 2;</code>
     */
    private $route_id = '';
    /**
     * corresponds to route_type in GTFS.
     * optional int32 route_type = 3;
     *
     * Generated from protobuf field <code>int32 route_type = 3;</code>
     */
    private $route_type = 0;
    /**
     * optional TripDescriptor trip = 4;
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.TripDescriptor trip = 4;</code>
     */
    private $trip = null;
    /**
     * optional string stop_id = 5;
     *
     * Generated from protobuf field <code>string stop_id = 5;</code>
     */
    private $stop_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $agency_id
     *           The values of the fields should correspond to the appropriate fields in the
     *           GTFS feed.
     *           At least one specifier must be given. If several are given, then the
     *           matching has to apply to all the given specifiers.
     *           optional string agency_id = 1;
     *     @type string $route_id
     *           optional string route_id = 2;
     *     @type int $route_type
     *           corresponds to route_type in GTFS.
     *           optional int32 route_type = 3;
     *     @type \FelixINX\TransitRealtime\TripDescriptor $trip
     *           optional TripDescriptor trip = 4;
     *     @type string $stop_id
     *           optional string stop_id = 5;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * optional string agency_id = 1;
     *
     * Generated from protobuf field <code>string agency_id = 1;</code>
     * @return string
     */
    public function getAgencyId()
    {
        return $this->agency_id;
    }

    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * optional string agency_id = 1;
     *
     * Generated from protobuf field <code>string agency_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAgencyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->agency_id = $var;

        return $this;
    }

    /**
     * optional string route_id = 2;
     *
     * Generated from protobuf field <code>string route_id = 2;</code>
     * @return string
     */
    public function getRouteId()
    {
        return $this->route_id;
    }

    /**
     * optional string route_id = 2;
     *
     * Generated from protobuf field <code>string route_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_id = $var;

        return $this;
    }

    /**
     * corresponds to route_type in GTFS.
     * optional int32 route_type = 3;
     *
     * Generated from protobuf field <code>int32 route_type = 3;</code>
     * @return int
     */
    public function getRouteType()
    {
        return $this->route_type;
    }

    /**
     * corresponds to route_type in GTFS.
     * optional int32 route_type = 3;
     *
     * Generated from protobuf field <code>int32 route_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRouteType($var)
    {
        GPBUtil::checkInt32($var);
        $this->route_type = $var;

        return $this;
    }

    /**
     * optional TripDescriptor trip = 4;
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.TripDescriptor trip = 4;</code>
     * @return \FelixINX\TransitRealtime\TripDescriptor
     */
    public function getTrip()
    {
        return $this->trip;
    }

    /**
     * optional TripDescriptor trip = 4;
     *
     * Generated from protobuf field <code>.FelixINX.TransitRealtime.TripDescriptor trip = 4;</code>
     * @param \FelixINX\TransitRealtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \FelixINX\TransitRealtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * optional string stop_id = 5;
     *
     * Generated from protobuf field <code>string stop_id = 5;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * optional string stop_id = 5;
     *
     * Generated from protobuf field <code>string stop_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

}

