<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\FeedHeader\Incrementality instead.
     * @deprecated
     */
    class FeedHeader_Incrementality {}
}
class_exists(FeedHeader\Incrementality::class);
@trigger_error('FelixINX\TransitRealtime\FeedHeader_Incrementality is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\FeedHeader\Incrementality instead', E_USER_DEPRECATED);

