<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\TranslatedString\Translation instead.
     * @deprecated
     */
    class TranslatedString_Translation {}
}
class_exists(TranslatedString\Translation::class);
@trigger_error('FelixINX\TransitRealtime\TranslatedString_Translation is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\TranslatedString\Translation instead', E_USER_DEPRECATED);

