<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\TripDescriptor\ScheduleRelationship instead.
     * @deprecated
     */
    class TripDescriptor_ScheduleRelationship {}
}
class_exists(TripDescriptor\ScheduleRelationship::class);
@trigger_error('FelixINX\TransitRealtime\TripDescriptor_ScheduleRelationship is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\TripDescriptor\ScheduleRelationship instead', E_USER_DEPRECATED);

