<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\TripUpdate\StopTimeUpdate\ScheduleRelationship instead.
     * @deprecated
     */
    class TripUpdate_StopTimeUpdate_ScheduleRelationship {}
}
class_exists(TripUpdate\StopTimeUpdate\ScheduleRelationship::class);
@trigger_error('FelixINX\TransitRealtime\TripUpdate_StopTimeUpdate_ScheduleRelationship is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\TripUpdate\StopTimeUpdate\ScheduleRelationship instead', E_USER_DEPRECATED);

