<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\TripUpdate\StopTimeUpdate instead.
     * @deprecated
     */
    class TripUpdate_StopTimeUpdate {}
}
class_exists(TripUpdate\StopTimeUpdate::class);
@trigger_error('FelixINX\TransitRealtime\TripUpdate_StopTimeUpdate is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\TripUpdate\StopTimeUpdate instead', E_USER_DEPRECATED);

