<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\TripUpdate\StopTimeEvent instead.
     * @deprecated
     */
    class TripUpdate_StopTimeEvent {}
}
class_exists(TripUpdate\StopTimeEvent::class);
@trigger_error('FelixINX\TransitRealtime\TripUpdate_StopTimeEvent is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\TripUpdate\StopTimeEvent instead', E_USER_DEPRECATED);

