<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\VehiclePosition\VehicleStopStatus instead.
     * @deprecated
     */
    class VehiclePosition_VehicleStopStatus {}
}
class_exists(VehiclePosition\VehicleStopStatus::class);
@trigger_error('FelixINX\TransitRealtime\VehiclePosition_VehicleStopStatus is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\VehiclePosition\VehicleStopStatus instead', E_USER_DEPRECATED);

