<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\VehiclePosition\CongestionLevel instead.
     * @deprecated
     */
    class VehiclePosition_CongestionLevel {}
}
class_exists(VehiclePosition\CongestionLevel::class);
@trigger_error('FelixINX\TransitRealtime\VehiclePosition_CongestionLevel is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\VehiclePosition\CongestionLevel instead', E_USER_DEPRECATED);

