<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime;

if (false) {
    /**
     * This class is deprecated. Use FelixINX\TransitRealtime\VehiclePosition\OccupancyStatus instead.
     * @deprecated
     */
    class VehiclePosition_OccupancyStatus {}
}
class_exists(VehiclePosition\OccupancyStatus::class);
@trigger_error('FelixINX\TransitRealtime\VehiclePosition_OccupancyStatus is deprecated and will be removed in the next major release. Use FelixINX\TransitRealtime\VehiclePosition\OccupancyStatus instead', E_USER_DEPRECATED);

