<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi\GPBMetadata;

class TransittrackerApi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�	
transittracker-api.protoTransitTracker.ProtobufApi"�	
VehiclesCollection
type (	H
features (26.TransitTracker.ProtobufApi.VehiclesCollection.Feature

lastRefreshAt (
�
Feature
type (	I
geometry (27.TransitTracker.ProtobufApi.VehiclesCollection.GeometryM

properties (29.TransitTracker.ProtobufApi.VehiclesCollection.Properties

id (
-
Geometry
type (	
coordinates (�

PropertiesA
trip (23.TransitTracker.ProtobufApi.VehiclesCollection.TripC
route (24.TransitTracker.ProtobufApi.VehiclesCollection.RouteG
vehicle (26.TransitTracker.ProtobufApi.VehiclesCollection.VehicleI
position (27.TransitTracker.ProtobufApi.VehiclesCollection.Position
currentStopSequence (


currentStatus (

	timestamp (

congestionLevel (

occupancyStatus	 (

vehicleType
 (

firstSeenAt (
�
Trip

id (	
	shortName (	
headsign (	
	startTime (	
scheduleRelationship (

blockId (	
shapeId (	Z
Route

id (	
	shortName (	
longName (	
color (	
	textColor (	:
Vehicle

id (	
label (	
licensePlate (	<
Position
bearing (

odometer (

speed (
bproto3'
        , true);

        static::$is_initialized = true;
    }
}

