<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TransitTracker.ProtobufApi.VehiclesCollection</code>
 */
class VehiclesCollection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>repeated .TransitTracker.ProtobufApi.VehiclesCollection.Feature features = 2;</code>
     */
    private $features;
    /**
     * Generated from protobuf field <code>uint32 lastRefreshAt = 3;</code>
     */
    protected $lastRefreshAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type array<\TransitTracker\ProtobufApi\VehiclesCollection\Feature>|\Google\Protobuf\Internal\RepeatedField $features
     *     @type int $lastRefreshAt
     * }
     */
    public function __construct($data = NULL) {
        \TransitTracker\ProtobufApi\GPBMetadata\TransittrackerApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .TransitTracker.ProtobufApi.VehiclesCollection.Feature features = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * Generated from protobuf field <code>repeated .TransitTracker.ProtobufApi.VehiclesCollection.Feature features = 2;</code>
     * @param array<\TransitTracker\ProtobufApi\VehiclesCollection\Feature>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, VehiclesCollection\Feature::class);
        $this->features = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 lastRefreshAt = 3;</code>
     * @return int
     */
    public function getLastRefreshAt()
    {
        return $this->lastRefreshAt;
    }

    /**
     * Generated from protobuf field <code>uint32 lastRefreshAt = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLastRefreshAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->lastRefreshAt = $var;

        return $this;
    }

}

