<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto3

namespace FelixINX\TransitRealtime\Alert;

/**
 * Cause of this alert.
 *
 * Protobuf type <code>FelixINX.TransitRealtime.Alert.Cause</code>
 */
class Cause
{
    /**
     * Generated from protobuf enum <code>PROTO3_DEFAULT_CAUSE = 0;</code>
     */
    const PROTO3_DEFAULT_CAUSE = 0;
    /**
     * Generated from protobuf enum <code>UNKNOWN_CAUSE = 1;</code>
     */
    const UNKNOWN_CAUSE = 1;
    /**
     * Not machine-representable.
     *
     * Generated from protobuf enum <code>OTHER_CAUSE = 2;</code>
     */
    const OTHER_CAUSE = 2;
    /**
     * Generated from protobuf enum <code>TECHNICAL_PROBLEM = 3;</code>
     */
    const TECHNICAL_PROBLEM = 3;
    /**
     * Public transit agency employees stopped working.
     *
     * Generated from protobuf enum <code>STRIKE = 4;</code>
     */
    const STRIKE = 4;
    /**
     * People are blocking the streets.
     *
     * Generated from protobuf enum <code>DEMONSTRATION = 5;</code>
     */
    const DEMONSTRATION = 5;
    /**
     * Generated from protobuf enum <code>ACCIDENT = 6;</code>
     */
    const ACCIDENT = 6;
    /**
     * Generated from protobuf enum <code>HOLIDAY = 7;</code>
     */
    const HOLIDAY = 7;
    /**
     * Generated from protobuf enum <code>WEATHER = 8;</code>
     */
    const WEATHER = 8;
    /**
     * Generated from protobuf enum <code>MAINTENANCE = 9;</code>
     */
    const MAINTENANCE = 9;
    /**
     * Generated from protobuf enum <code>CONSTRUCTION = 10;</code>
     */
    const CONSTRUCTION = 10;
    /**
     * Generated from protobuf enum <code>POLICE_ACTIVITY = 11;</code>
     */
    const POLICE_ACTIVITY = 11;
    /**
     * Generated from protobuf enum <code>MEDICAL_EMERGENCY = 12;</code>
     */
    const MEDICAL_EMERGENCY = 12;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Cause::class, \FelixINX\TransitRealtime\Alert_Cause::class);

