<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi\VehiclesCollection;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TransitTracker.ProtobufApi.VehiclesCollection.Properties</code>
 */
class Properties extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Trip trip = 1;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Route route = 2;</code>
     */
    protected $route = null;
    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Vehicle vehicle = 3;</code>
     */
    protected $vehicle = null;
    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Position position = 4;</code>
     */
    protected $position = null;
    /**
     * Generated from protobuf field <code>uint32 currentStopSequence = 5;</code>
     */
    protected $currentStopSequence = 0;
    /**
     * Generated from protobuf field <code>uint32 currentStatus = 6;</code>
     */
    protected $currentStatus = 0;
    /**
     * Generated from protobuf field <code>uint32 timestamp = 7;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint32 congestionLevel = 8;</code>
     */
    protected $congestionLevel = 0;
    /**
     * Generated from protobuf field <code>uint32 occupancyStatus = 9;</code>
     */
    protected $occupancyStatus = 0;
    /**
     * Generated from protobuf field <code>uint32 vehicleType = 10;</code>
     */
    protected $vehicleType = 0;
    /**
     * Generated from protobuf field <code>uint32 firstSeenAt = 11;</code>
     */
    protected $firstSeenAt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \TransitTracker\ProtobufApi\VehiclesCollection\Trip $trip
     *     @type \TransitTracker\ProtobufApi\VehiclesCollection\Route $route
     *     @type \TransitTracker\ProtobufApi\VehiclesCollection\Vehicle $vehicle
     *     @type \TransitTracker\ProtobufApi\VehiclesCollection\Position $position
     *     @type int $currentStopSequence
     *     @type int $currentStatus
     *     @type int $timestamp
     *     @type int $congestionLevel
     *     @type int $occupancyStatus
     *     @type int $vehicleType
     *     @type int $firstSeenAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransittrackerApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Trip trip = 1;</code>
     * @return \TransitTracker\ProtobufApi\VehiclesCollection\Trip|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Trip trip = 1;</code>
     * @param \TransitTracker\ProtobufApi\VehiclesCollection\Trip $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \TransitTracker\ProtobufApi\VehiclesCollection\Trip::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Route route = 2;</code>
     * @return \TransitTracker\ProtobufApi\VehiclesCollection\Route|null
     */
    public function getRoute()
    {
        return $this->route;
    }

    public function hasRoute()
    {
        return isset($this->route);
    }

    public function clearRoute()
    {
        unset($this->route);
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Route route = 2;</code>
     * @param \TransitTracker\ProtobufApi\VehiclesCollection\Route $var
     * @return $this
     */
    public function setRoute($var)
    {
        GPBUtil::checkMessage($var, \TransitTracker\ProtobufApi\VehiclesCollection\Route::class);
        $this->route = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Vehicle vehicle = 3;</code>
     * @return \TransitTracker\ProtobufApi\VehiclesCollection\Vehicle|null
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    public function hasVehicle()
    {
        return isset($this->vehicle);
    }

    public function clearVehicle()
    {
        unset($this->vehicle);
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Vehicle vehicle = 3;</code>
     * @param \TransitTracker\ProtobufApi\VehiclesCollection\Vehicle $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \TransitTracker\ProtobufApi\VehiclesCollection\Vehicle::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Position position = 4;</code>
     * @return \TransitTracker\ProtobufApi\VehiclesCollection\Position|null
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function hasPosition()
    {
        return isset($this->position);
    }

    public function clearPosition()
    {
        unset($this->position);
    }

    /**
     * Generated from protobuf field <code>.TransitTracker.ProtobufApi.VehiclesCollection.Position position = 4;</code>
     * @param \TransitTracker\ProtobufApi\VehiclesCollection\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \TransitTracker\ProtobufApi\VehiclesCollection\Position::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 currentStopSequence = 5;</code>
     * @return int
     */
    public function getCurrentStopSequence()
    {
        return $this->currentStopSequence;
    }

    /**
     * Generated from protobuf field <code>uint32 currentStopSequence = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->currentStopSequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 currentStatus = 6;</code>
     * @return int
     */
    public function getCurrentStatus()
    {
        return $this->currentStatus;
    }

    /**
     * Generated from protobuf field <code>uint32 currentStatus = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->currentStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 7;</code>
     * @return int
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint32 timestamp = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint32($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 congestionLevel = 8;</code>
     * @return int
     */
    public function getCongestionLevel()
    {
        return $this->congestionLevel;
    }

    /**
     * Generated from protobuf field <code>uint32 congestionLevel = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setCongestionLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->congestionLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 occupancyStatus = 9;</code>
     * @return int
     */
    public function getOccupancyStatus()
    {
        return $this->occupancyStatus;
    }

    /**
     * Generated from protobuf field <code>uint32 occupancyStatus = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOccupancyStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->occupancyStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 vehicleType = 10;</code>
     * @return int
     */
    public function getVehicleType()
    {
        return $this->vehicleType;
    }

    /**
     * Generated from protobuf field <code>uint32 vehicleType = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setVehicleType($var)
    {
        GPBUtil::checkUint32($var);
        $this->vehicleType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 firstSeenAt = 11;</code>
     * @return int
     */
    public function getFirstSeenAt()
    {
        return $this->firstSeenAt;
    }

    /**
     * Generated from protobuf field <code>uint32 firstSeenAt = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setFirstSeenAt($var)
    {
        GPBUtil::checkUint32($var);
        $this->firstSeenAt = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Properties::class, \TransitTracker\ProtobufApi\VehiclesCollection_Properties::class);

