<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi\VehiclesCollection;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TransitTracker.ProtobufApi.VehiclesCollection.Route</code>
 */
class Route extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     */
    protected $shortName = '';
    /**
     * Generated from protobuf field <code>string longName = 3;</code>
     */
    protected $longName = '';
    /**
     * Generated from protobuf field <code>string color = 4;</code>
     */
    protected $color = '';
    /**
     * Generated from protobuf field <code>string textColor = 5;</code>
     */
    protected $textColor = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $shortName
     *     @type string $longName
     *     @type string $color
     *     @type string $textColor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransittrackerApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     * @return string
     */
    public function getShortName()
    {
        return $this->shortName;
    }

    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shortName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string longName = 3;</code>
     * @return string
     */
    public function getLongName()
    {
        return $this->longName;
    }

    /**
     * Generated from protobuf field <code>string longName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLongName($var)
    {
        GPBUtil::checkString($var, True);
        $this->longName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string color = 4;</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>string color = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string textColor = 5;</code>
     * @return string
     */
    public function getTextColor()
    {
        return $this->textColor;
    }

    /**
     * Generated from protobuf field <code>string textColor = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTextColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->textColor = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Route::class, \TransitTracker\ProtobufApi\VehiclesCollection_Route::class);

