<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi\VehiclesCollection;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TransitTracker.ProtobufApi.VehiclesCollection.Trip</code>
 */
class Trip extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     */
    protected $shortName = '';
    /**
     * Generated from protobuf field <code>string headsign = 3;</code>
     */
    protected $headsign = '';
    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     */
    protected $startTime = '';
    /**
     * Generated from protobuf field <code>uint32 scheduleRelationship = 5;</code>
     */
    protected $scheduleRelationship = 0;
    /**
     * Generated from protobuf field <code>string blockId = 6;</code>
     */
    protected $blockId = '';
    /**
     * Generated from protobuf field <code>string shapeId = 7;</code>
     */
    protected $shapeId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $shortName
     *     @type string $headsign
     *     @type string $startTime
     *     @type int $scheduleRelationship
     *     @type string $blockId
     *     @type string $shapeId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransittrackerApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     * @return string
     */
    public function getShortName()
    {
        return $this->shortName;
    }

    /**
     * Generated from protobuf field <code>string shortName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shortName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string headsign = 3;</code>
     * @return string
     */
    public function getHeadsign()
    {
        return $this->headsign;
    }

    /**
     * Generated from protobuf field <code>string headsign = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadsign($var)
    {
        GPBUtil::checkString($var, True);
        $this->headsign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Generated from protobuf field <code>string startTime = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->startTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 scheduleRelationship = 5;</code>
     * @return int
     */
    public function getScheduleRelationship()
    {
        return $this->scheduleRelationship;
    }

    /**
     * Generated from protobuf field <code>uint32 scheduleRelationship = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setScheduleRelationship($var)
    {
        GPBUtil::checkUint32($var);
        $this->scheduleRelationship = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string blockId = 6;</code>
     * @return string
     */
    public function getBlockId()
    {
        return $this->blockId;
    }

    /**
     * Generated from protobuf field <code>string blockId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockId($var)
    {
        GPBUtil::checkString($var, True);
        $this->blockId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shapeId = 7;</code>
     * @return string
     */
    public function getShapeId()
    {
        return $this->shapeId;
    }

    /**
     * Generated from protobuf field <code>string shapeId = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setShapeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shapeId = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Trip::class, \TransitTracker\ProtobufApi\VehiclesCollection_Trip::class);

