<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transittracker-api.proto

namespace TransitTracker\ProtobufApi\VehiclesCollection;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TransitTracker.ProtobufApi.VehiclesCollection.Vehicle</code>
 */
class Vehicle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string label = 2;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string licensePlate = 3;</code>
     */
    protected $licensePlate = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $label
     *     @type string $licensePlate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransittrackerApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string licensePlate = 3;</code>
     * @return string
     */
    public function getLicensePlate()
    {
        return $this->licensePlate;
    }

    /**
     * Generated from protobuf field <code>string licensePlate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLicensePlate($var)
    {
        GPBUtil::checkString($var, True);
        $this->licensePlate = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Vehicle::class, \TransitTracker\ProtobufApi\VehiclesCollection_Vehicle::class);

